name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=yiweiyuntian --password=CHUxue2005 registry.us-east-1.aliyuncs.com
          cd one-api
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.us-east-1.aliyuncs.com/yiweionline/onepai2:2.4.1
          # 推送镜像到镜像仓库
          docker push registry.us-east-1.aliyuncs.com/yiweionline/onepai2:2.4.1
